import type { DeviceInfo } from '@/api/types/deviceInfoTypes.uts'

export type AdItem = {
	id : number;
	title : string;
	src : string;
	type : 'video' | 'image';
}
export type State = {
	machineCode:string;
	adList : dFile[];
	goodsList : dFile[];
	petWashInfo : DeviceInfo[];
	petWash:DeviceInfo | null;
	showPay:boolean;
}
export type GetMediaInfo = GetImageInfoSuccess | GetVideoInfoSuccess | null | false

export type dFile = {
	data : AdItem;
	path : string;
	fileName : string;
	mediaInfo : GetMediaInfo
}
// export interface dFile<T> {
//   ad:T;
//   tempFilePath:string;
//   fileName:string
// }
export type DownloadFile = Promise<DownloadFileSuccessCallback | dFile | null | undefined | false>