
export type AdItem = {
	id : number;
	title : string;
	src : string;
	type : 'video' | 'image';
}
export type State = {
	adList : AdItem[];

}
export type GetMediaInfo = GetImageInfoSuccess | GetVideoInfoSuccess | null | false

export type dFile = {
	data : AdItem;
	path : string;
	fileName : string;
	mediaInfo : GetMediaInfo
}
// export interface dFile<T> {
//   ad:T;
//   tempFilePath:string;
//   fileName:string
// }
