/**
 * 设备状态
 */
export type DeviceData = {
	/** 洗护模式 */
	mode: 'dry' | 'basis' | 'enhance',
	/** 洗宠机状态 */
	status:  5 | 10 | 15 | 20 | 30 | 40 | 50 | 60 | 70 | 80 | 90 | 100 | 110 | 120,
	/** 室温 */
	cage:number,
	/** 水温 */
	water:number,
	/** 宠物重量 */
	petWeight:number,
	/** 倒计时 */
	countdownTime:number,
}

/**
 * 全局参数
 */
export type GlobalState = {
	/** 设备码 */
	machineCode:string,
	/** 设备状态 */
  deviceData: DeviceData,
	/** 当前订单 */
	order_id:string,
	/** 串口连接状态 */
	notConnected:boolean,
	/** 版本号 */
	appVersion:string,
	/** 更新状态 */
	updating:boolean,
}