
/**
 * 自动转换任意值为布尔值
 * @param value 任意输入值
 * @returns boolean
 */
export function toBoolean(value : any) : boolean {
	if (value == null) return false;
	if (typeof value == "boolean") return value;
	if (typeof value == "number") return value !== 0;
	if (typeof value == "string") {
		const v = value.trim().toLowerCase();
		if (["true", "1", "yes", "on"].includes(v)) return true;
		if (["false", "0", "no", "off", ""].includes(v)) return false;
		// 其他字符串非空 → true
		return true;
	}
	// 对象、数组 → true
	return true;
}

export function getErrorMsg(code : number) : string {
	let strCode = `${code}`
	const errorMessageMap = {
		'400': '请求错误',
		'401': '请先登录', // 登录状态会单独判断
		'403': '拒绝访问',
		'404': '请求出错',
		'408': '请求超时',
		'429': '请求频繁, 请稍后再访问',
		'500': '服务器开小差啦,请稍后再试~',
		'501': '服务未实现',
		'502': '网络错误',
		'503': '服务不可用',
		'504': '网络超时',
		'505': 'HTTP版本不受支持',
	};
	if (UTSJSONObject.keys(errorMessageMap).includes(strCode)) {
		return errorMessageMap[strCode] as string
	} else {
		return `网络请求错误:${strCode}`
	}
}
/**
 * 将任意对象安全转换为指定类型
 */
export function toNewObject<T>(obj: any): T {
	try{
		return UTSJSONObject.assign<T>(obj as UTSJSONObject)!;
	}catch(err){
		console.log('toNewObject --- error',err)
		let errData = JSON.parse<T>(JSON.stringify(obj))!
		return errData
	}
}
/**
 * 将任意数组安全转换为指定类型
 */
export function toNewArray<T>(obj: any): T[]{
	try {
		const arr = obj as any[]
		const result: any[] = []
		for (let i = 0; i < arr.length; i++) {
			const res = arr[i] as UTSJSONObject
			result.push(UTSJSONObject.assign<T>(res)!)
		}
		return result as T[]
	} catch (err) {
		console.log('toNewArray --- error',err)
		return []
	}
}
export function showMsg(title : string, duration : number = 1500, mask : boolean = true) {
	uni.showToast({
		title,
		icon: "none",
		mask,
		duration,
	});
}