import { baseUrl } from "@/config.uts"
import { getErrorMsg,showMsg ,toNewObject} from "@/utils/tools.uts"

// 自定义配置
type CustomConfig = {
	showError : boolean;
	showSuccess : boolean;
}

// request 参数
export type RequestConfig = {
	url : string;
	method ?: string;
	data ?: any;    // 不能用索引签名，直接 any
	params ?: any;
	header ?: any;
	custom ?: CustomConfig;
}

// 返回数据
export type ResponseData = {
	error ?: number;
	msg ?: string;
	// ❌ 这里不能写 [key: string]: any
	data : any; // 如果需要扩展，定义一个 data 就行
}

function request(config : RequestConfig) : Promise<ResponseData> {
	return new Promise((resolve, reject) => {
		// 先构建 headers
		let headers : UTSJSONObject = {
			Accept: "text/json",
			"Content-Type": "application/json;charset=UTF-8"
		}

		if (config.header != null) {
			headers = UTSJSONObject.assign(headers, config.header as UTSJSONObject)
		}
		uni.request({
			url: (config.url.startsWith("http") ? "" : baseUrl) + config.url,
			timeout: 20000,
			method: config.method ?? "GET",
			data:  config.data ?? ( config.params ?? {}),
			header: headers,
			success:(response)=>{
				let msg:string
				if (response.statusCode == 200) {
					// const data = JSON.parse<ResponseData>(JSON.stringify(response.data));
					const data = toNewObject<ResponseData>(response.data!)
					if (data?.error == 0) {
						if (config.custom != null) {
							if (config.custom.showSuccess == true && data.msg != null) {
								showMsg(data.msg)
							}
						}
						resolve(data);
					} else {
						if (config.custom != null) {
							if (config.custom.showError == true && data?.msg != null) {
								showMsg(data.msg)
							}
						}
						reject({
							error: data?.error ?? -1,
							msg: data?.msg ?? "业务错误",
							raw: response
						});
					}
				} else {
					msg = getErrorMsg(response.statusCode)
					if (config.custom != null && config.custom.showError == true) {
						showMsg(msg)
					}
					reject({
						error: response.statusCode,
						msg,
						raw: response
					});
				}
			},
			fail:(error)=>{
				if (config.custom != null) {
					if (config.custom.showError == true) {
						showMsg(error.errMsg)
					}
				}
				reject({
					error: error.errCode,
					msg:error.errMsg,
					raw: error
				});
			},

		});
	});
}

export {
	request
}