import { baseUrl } from "@/config.uts"
import { toBoolean } from "@/utils/tools.uts"

// 自定义配置
interface CustomConfig {
  showError: boolean;
}

// request 参数
export interface RequestConfig {
  url: string;
  method?: string;
  data?: any;    // 不能用索引签名，直接 any
  params?: any;
  header?: any;
  custom?: CustomConfig;
}

// 返回数据
interface ResponseData {
  error?: number;
  msg?: string;
  // ❌ 这里不能写 [key: string]: any
  data?: any; // 如果需要扩展，定义一个 data 就行
}

function request(config: RequestConfig): Promise<ResponseData | false> {
  return new Promise((resolve, reject) => {
		// 先构建 headers
		let headers:UTSJSONObject  = {
		  Accept: "text/json",
		  "Content-Type": "application/json;charset=UTF-8"
		}
		
		if (config.header != null) {
		  UTSJSONObject.assign(headers, config.header as UTSJSONObject )
		}
    uni.request({
      url: (config.url.startsWith("http") ? "" : baseUrl) + config.url,
      timeout: 10000,
      method: config.method != null ? config.method : "GET",
      data: config.data != null ? config.data : (config.params != null ? config.params : {}),
      header:headers,
      success: (response) => {
        const data = response.data as ResponseData;
        if (data.error !== 0) {
          if (toBoolean(config.custom as any) && toBoolean(config.custom?.showError as any)) {
            uni.showToast({
              title: toBoolean(data?.msg as any) ? data.msg :  "网络请求出错",
              icon: "none",
              mask: true,
              duration: 1500,
            });
          }
        }
        resolve(data);
      },
      fail: (error) => {
        if (toBoolean(config.custom as any) && toBoolean(config.custom?.showError as any)) {
          uni.showToast({
            title: toBoolean(error.data?.msg as any) ?  error.data.msg :  "网络请求失败",
            icon: "none",
            mask: true,
          });
        }
        resolve(false);
      },
    });
  });
}

export {
  request
}
